src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LessonRepository::class)]
class Lesson
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    private ?Training $training = null;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    private ?Person $instructor = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $time = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column]
    private ?int $max_persons = null;

    #[ORM\OneToMany(mappedBy: 'lesson', targetEntity: Registration::class)]
    private Collection $registrations;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?bool $isSignedUp = false;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTraining(): ?Training
    {
        return $this->training;
    }

    public function setTraining(?Training $training): self
    {
        $this->training = $training;

        return $this;
    }

    public function getInstructor(): ?Person
    {
        return $this->instructor;
    }

    public function setInstructor(?Person $instructor): self
    {
        $this->instructor = $instructor;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMaxPersons(): ?int
    {
        return $this->max_persons;
    }

    public function setMaxPersons(int $max_persons): self
    {
        $this->max_persons = $max_persons;

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setLesson($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getLesson() === $this) {
                $registration->setLesson(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function isIsSignedUp(): ?bool
    {
        return $this->isSignedUp;
    }

    public function setIsSignedUp(bool $isSignedUp): self
    {
        $this->isSignedUp = $isSignedUp;

        return $this;
    }
}

src/Controller/KlantController.php
<?php

namespace App\Controller;

use App\Entity\Lesson;
use App\Form\ProfileType;
use App\Entity\Registration;
use App\Entity\Training;
use App\Form\RegisterLessonType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\LessonRepository;
use App\Repository\TrainingRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class KlantController extends AbstractController
{

    #[Route('/klant', name: 'app_klant')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $lessons = $doctrine->getRepository(Lesson::class)->findAll();
        return $this->render('klant/index.html.twig', [
            'lessons' => $lessons
        ]);
    }

//    #[Route('/activity/{id}', name: 'activity')]
//    public function activities(ManagerRegistry $doctrine, Lesson::class): Response
//    {
//
//
//    }

//    #[Route('/activity/{id}', name: 'activity_details')]
//    public function activityDetails($id): Response
//    {
//        $entityManager = $this->getDoctrine()->getManager();
//        $lessons = $entityManager->getRepository(Lesson::class)->find($id);
//
//        return $this->render('klant/activities.html.twig', [
//            'lessons' => $lessons,
//        ]);
//    }

//    #[Route('/activity/{id}', name: 'activity_details')]
//    public function activityDetails(ManagerRegistry $doctrine, int $id, TrainingRepository $lessonRepository): Response
//    {
//        $entityManager = $doctrine->getManager();
//
//        $lesson = $lessonRepository->find($id);
//        $lessons = $entityManager->getRepository(Lesson::class)->findAll();
//
//        return $this->render('klant/activities.html.twig', [
//            'lesson' => $lesson,
//            'lessons' => $lessons
//        ]);
//    }

    #[Route('/activity/{id}', name: 'activity_details')]
    public function activityDetails(int $id, LessonRepository $lessonRepository): Response
    {
        $lesson = $lessonRepository->find($id);

        if(!$lesson){
            throw $this->createNotFoundException('Lesson not found');
        }

        return $this->render('klant/activities.html.twig', [
            'lesson' => $lesson,
        ]);
    }

//    #[Route('/signup/{id}', name: 'signup')]
//    public function lessonSignUp(int $id, EntityManagerInterface $entityManager): Response
//    {
//        // Get the lesson by its ID
//        $lesson = $entityManager->getRepository(Lesson::class)->find($id);
//
//        // Update the isSignedUp flag to true
//        $lesson->setIsSignedUp(true);
//
//        // Save the changes to the database
//        $entityManager->persist($lesson);
//        $entityManager->flush();
//
//        // Redirect to a success page or perform any other desired action
//        return $this->redirectToRoute('success_page');
//    }

    #[Route('/klant/lesson/add/{id}', name:'signup')]
    public function addKlant(Request $request, EntityManagerInterface $entityManager) : Response
    {
        $add = new Registration();
        $add->setPerson($this->getUser());

        $form = $this->createForm(RegisterLessonType::class, $add);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $klant = $form->getData();
            $entityManager->persist($klant);
            $entityManager->flush();

            return $this->redirectToRoute('app_klant');
        }
        return $this->renderForm('klant/success.html.twig' , [
            'form' => $form
        ]);





    }

    #[Route('/succes', name: 'success_page')]
    public function success()
    {
        return $this->render('klant/success.html.twig');
    }

    #[Route('/leave-activity/{id}', name: 'leave_activity')]
    public function leaveActivity(int $id, EntityManagerInterface $entityManager): Response
    {
        // Get the lesson by its ID
        $lesson = $entityManager->getRepository(Lesson::class)->find($id);

        // Update the isSignedUp flag to false
        $lesson->setIsSignedUp(false);

        // Save the changes to the database
        $entityManager->persist($lesson);
        $entityManager->flush();

        // Redirect to a success page or perform any other desired action
        return $this->redirectToRoute('leave_page');
    }

    #[Route('/leave', name: 'leave_page')]
    public function leave()
    {
        return $this->render('klant/leave.html.twig');
    }



    #[Route('/update-profile', name: 'update_profile')]
    public function updateProfile(Request $request): Response
    {
        // Get the authenticated user
        $user = $this->getUser();

        // Create the form and handle the request
        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Persist the updated data
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            // Redirect or show a success message
            return $this->redirectToRoute('update_success_page');
        }

        return $this->render('klant/update_profile.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/update-success', name:'update_success_page')]
    public function updateSucces()
    {
        return $this->render('klant/update_success_page.html.twig');
    }





}

templates/klant/activities.html.twig
{% extends 'base.html.twig' %}

{% block body %}

        <h3>{{ lesson.title }}</h3>

        <br>
        <p>Date: {{ lesson.date|date('d-m-Y') }} </p>
        <p>Time: {{ lesson.time|date('H:i') }} </p>
        <p>Location: {{ lesson.location }}</p>
        <p>Max Persons: {{ lesson.maxPersons }}</p>

        {% if not lesson.isSignedUp %}
                <a href="{{ path('signup', {'id': lesson.id}) }}">Sign Up</a>
        {% else %}
                <form action="{{ path('leave_activity', {'id': lesson.id}) }}" method="POST">
                <p>You are already signed up for this lesson.</p>
                <button type="submit">Leave Activity</button>
        {% endif %}


{% endblock %}

templates/klant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello KlantController!{% endblock %}

{% block body %}




    <nav class="navbar navbar-light bg-light p-3">
        <div class="d-flex col-12 col-md-3 col-lg-2 mb-2 mb-lg-0 flex-wrap flex-md-nowrap justify-content-between">
            <a class="navbar-brand" href="#">
                <p>Welkom Member {% if app.user %} {{ app.user.firstname }}! {% endif %}</p>
            </a>
            <button class="navbar-toggler d-md-none collapsed mb-3" type="button" data-toggle="collapse" data-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-gear"></i>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" href="{{ path('update_profile') }}">Settings</a></li>
                <li><a class="dropdown-item" href="#">Messages</a></li>
                <li><a class="dropdown-item" href="{{ path('logout') }}">Sign out</a></li>
            </ul>
        </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                <span class="ml-2">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                                <span class="ml-2">My activities</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                                <span class="ml-2">Open activites</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                                <span class="ml-2">Information</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-sm btn-primary ml-3 mt-2" href="#">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M1 2.828v9.923c.918-.35 2.107-.692 3.287-.81 1.094-.111 2.278-.039 3.213.492V2.687c-.654-.689-1.782-.886-3.112-.752-1.234.124-2.503.523-3.388.893zm7.5-.141v9.746c.935-.53 2.12-.603 3.213-.493 1.18.12 2.37.461 3.287.811V2.828c-.885-.37-2.154-.769-3.388-.893-1.33-.134-2.458.063-3.112.752zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                                </svg>
                                <span class="ml-2">Read the Rules ❤️</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Overview</li>
                    </ol>
                </nav>
                <h1 class="h2">Dashboard</h1>
                <br>
                <h4>Your Activities</h4>
                <div class="row my-4">
                    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
                        <div class="card">
                            <h5 class="card-header"></h5>
                            <div class="card-body">
                                <h5 class="card-title"></h5>
                                <p class="card-text"></p>
                                <p class="card-text text-success"></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-xl-12 mb-4 mb-lg-0">
                        <div class="card">
                            <h5 class="card-header">Featured Lessons</h5>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th scope="col">Name</th>
                                            <th scope="col">Time</th>
                                            <th scope="col">Location</th>
                                            <th scope="col">Date</th>
                                            <th scope="col"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for lesson in lessons %}
                                        <tr>
                                            <th scope="row">{{ lesson.title }}</th>
                                            <td>{{ lesson.time|date('H:i')}}</td>
                                            <td>{{ lesson.location }}</td>
                                            <td>{{ lesson.date|date('d-m-Y') }}</td>
                                            <td><a href="{{ path('activity_details', {id: lesson.id}) }}" class="btn btn-sm btn-primary">View</a></td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <a href="#" class="btn btn-block btn-light">View all</a>
                            </div>
                        </div>
                    </div>

                    <footer class="pt-5 d-flex justify-content-between">
                        <span>Copyright © 2023 TrainingFactory | All rights reserved </span>
                        <ul class="nav m-0">
                            <li class="nav-item">
                                <a class="nav-link text-secondary" aria-current="page" href="#">Privacy Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-secondary" href="#">Terms and conditions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-secondary" href="#">Contact</a>
                            </li>
                        </ul>
                    </footer>
            </main>
        </div>
    </div>


{% endblock %}

templates/klant/leave.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Jammer dat je de activiteit hebt verlaten!</h1>

{% endblock %}

templates/klant/success.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form(form) }}

    <h1>We hebben je ingeschreven</h1>

{% endblock %}

templates/klant/update_profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <div class="row">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Save Changes</button>
            {{ form_end(form) }}
        </div>
    </div>


{% endblock %}

templates/klant/update_success_page.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Gegevens zijn bijgewerkt</h1>

{% endblock %}